Panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.inicio.urls')),
    path('productos/',include('apps.productos.urls')),
    path('',include('apps.pedidos.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('empleados/',include('apps.usuarios.urls')),
]

apps/usuarios/urls.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path
from . import views

app_name = 'usuarios'

def admin_required(user):
    return user.is_superuser  # Solo permite acceso a superusuarios


urlpatterns = [
    path('', user_passes_test(admin_required)(login_required(views.empleados)), name='empleados'),
    path('buscarEmpleado/',user_passes_test(admin_required)(login_required(views.buscarEmpleado)), name='buscarEmpleado'),
    path('eliminarEmpleado/<empleado_id>',user_passes_test(admin_required)(login_required(views.eliminarEmpleado)), name='eliminarEmpleado'),
    path('editarEmpleado/<empleado_id>',user_passes_test(admin_required)(login_required(views.editarEmpleado)),name='editarEmpleado'),
    path('edicionEmpleado/',user_passes_test(admin_required)(login_required(views.edicionEmpleado)),name='edicionEmpleado'),
    path('agregarEmpleado',user_passes_test(admin_required)(login_required(views.agregarEmpleado)),name='agregarEmpleado'),
    path('crear_usuario/', user_passes_test(admin_required)(login_required(views.crear_usuario)), name='crear_usuario'),
    path('generarPDF/', user_passes_test(admin_required)(login_required(views.generarPDF)), name='generarPDF'),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50,blank=False,null=False)
    apellido = models.CharField(max_length=50,blank=False,null=False)
    direccion  = models.CharField(max_length=50,blank=False,null=False)
    telefono = models.CharField(max_length=15,blank=False,null=False)
    mail = models.EmailField(blank=True,null=True)
    
    class Meta:
        abstract = True  # Esto hace que no se genere una tabla en la BD
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
class Empleado(Persona):
    ESTADO = [
        ('activo', 'Activo'),
        ('inactivo', 'Inactivo'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user')
    dni  = models.CharField(max_length=8,blank=False,null=False)
    fechaDeNacimiento = models.DateField(blank=False,null=False)
    fechaDeIngreso = models.DateField(blank=False,null=False)
    salario = models.DecimalField(max_digits=10,blank=False,null=False,decimal_places=2)
    estado = models.CharField(max_length=10,choices=ESTADO,blank=False,null=False,default='activo')
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}, DNI: {self.dni}"
    

apps/usuarios/forms.py
from django import forms
from .models import Empleado
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext as _


class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['nombre', 'apellido', 'dni', 'direccion', 'telefono', 'mail', 'fechaDeNacimiento', 'fechaDeIngreso', 'salario','user','estado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}), 
            'apellido': forms.TextInput(attrs={'class':'form-control'}), 
            'dni': forms.TextInput(attrs={'class':'form-control'}), 
            'direccion': forms.TextInput(attrs={'class':'form-control'}), 
            'telefono': forms.TextInput(attrs={'class':'form-control'}),  
            'mail': forms.EmailInput(attrs={'class': 'form-control'}),
            'salario': forms.NumberInput(attrs={'class':'form-control'}),
            'estado': forms.Select(attrs={'class':'form-control'}),
            'fechaDeNacimiento': forms.DateInput(attrs={'type': 'date','class':'form-control'}),
            'fechaDeIngreso': forms.DateInput(attrs={'type': 'date','class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = User.objects.filter(is_active=True)  # Mostrar solo usuarios activos
        
class CrearUsuario(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Añadir clase 'form-control' a todos los campos del formulario
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Las contraseñas no coinciden."), code='password_mismatch')
        
        if len(password2) < 8:
            raise forms.ValidationError(_("La contraseña debe tener al menos 8 caracteres."), code='password_too_short')
        
        return password2

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(_("Este nombre de usuario ya está en uso."), code='username_taken')
        return username

apps/usuarios/views.py
from django.conf import settings
from datetime import datetime
import os
from django.http import HttpResponse
from django.shortcuts import render, redirect
from fpdf import FPDF
from Panaderia import settings
from .forms import EmpleadoForm, CrearUsuario
from django.contrib.auth.models import User
from apps.usuarios.models import Empleado
from django.contrib import messages

def empleados(request):
    empleados = Empleado.objects.all()
    return render(request, 'usuarios/empleados.html', {'empleados': empleados})

def buscarEmpleado(request):
    busqueda = request.POST['busqueda']
    empleados = Empleado.objects.all()
    if busqueda: 
        empleados = empleados.filter(dni__icontains=busqueda)
    return render(request, 'usuarios/empleados.html', {'empleados': empleados, 'busqueda': busqueda})

def eliminarEmpleado(request,empleado_id):
    empleado = Empleado.objects.get(id=empleado_id)
    empleado.estado='inactivo'
    empleado.save()
    return redirect('usuarios:empleados')

def editarEmpleado(request,empleado_id):
    empleado = Empleado.objects.get(id=empleado_id)
    return render(request,'usuarios/edicionEmpleados.html',{'empleado':empleado})

def edicionEmpleado(request):
    if request.method == 'POST':  
        empleado_id = request.POST.get('id')
        empleado = Empleado.objects.get(id=empleado_id)
        empleado.nombre = request.POST['nombre']
        empleado.apellido = request.POST['apellido']
        empleado.dni = request.POST['dni']
        empleado.direccion = request.POST['direccion']
        empleado.telefono = request.POST['telefono']
        empleado.mail = request.POST['mail']
        empleado.fechaDeNacimiento = request.POST['fechaDeNacimiento']
        empleado.salario = request.POST['salario']
        empleado.fechaDeIngreso = request.POST['fechaDeIngreso']
        empleado.estado = request.POST['estado']
        empleado.save()  
        
    return redirect('usuarios:empleados')  


def agregarEmpleado(request):
    if request.method == "POST":
        form = EmpleadoForm(request.POST)
        if form.is_valid(): 
            form.save()
            messages.success(request, "Empleado agregado con éxito.")
            return redirect('usuarios:empleados')  
    else:
        form = EmpleadoForm() 
    return render(request, 'usuarios/agregarEmpleado.html', {'form': form})

def crear_usuario(request):
    if request.method == "POST":
        form = CrearUsuario(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "Usuario creado con éxito.")
            return redirect('usuarios:agregarEmpleado')  
    else:
        form = CrearUsuario()
    return render(request, 'usuarios/crear_usuario.html', {'form': form})

def diccionario_colores(color): 
    colores = {
        'black' : (0,0,0), 
        'white' : (255,255,255),
        'green' : (96,218,117),
        'blue' : (96,181,218),
        'red': (119,30,48),
        'rose':(214,74,236),
        'gray':(103,103,103),
        'gray2':(233,233,233),
        }

    return colores[color]

def dcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_draw_color(r= cr, g = cg, b= cb)

def bcol_set(hoja,color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_fill_color(r= cr, g = cg, b= cb)

def tcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_text_color(r= cr, g = cg, b= cb)

def tfont_size(hoja, size):
    hoja.set_font_size(size)

def tfont(hoja, estilo, fuente='Arial'):
    hoja.set_font(fuente, style=estilo)



class PDF(FPDF):
    def __init__(self, title):
        super().__init__()
        self.title = title
    
    def header(self):
        logo = os.path.join(settings.BASE_DIR, 'static', 'img', 'logotipo.png')
        
        # Verificar si el archivo existe
        if os.path.exists(logo):
            self.image(logo, x=10, y=10, w=30, h=30) 
        
        self.set_font('Arial', '', 15)

        tcol_set(self, 'red')
        tfont_size(self,30)
        tfont(self,'B')
        self.cell(w = 0, h = 20, txt = self.title, border = 0, ln=1,
                align = 'C', fill = 0)

        tfont_size(self,10)
        tcol_set(self, 'black')
        tfont(self,'I')
        self.cell(w = 0, h = 10, txt = f'Generado el {datetime.now().strftime("%d/%m/%y")}', border = 0, ln=2,
                align = 'C', fill = 0)

        self.ln(5)

    # Page footer
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-20)

        # Arial italic 8
        self.set_font('Arial', 'I', 12)

        # Page number
        self.cell(w = 0, h = 10, txt =  'Pagina ' + str(self.page_no()),
                 border = 0,
                align = 'C', fill = 0)

def generarPDF(request):
    # Crear un objeto FPDF
    pdf = PDF("Reporte de empleados")
    pdf.add_page()
    
    # Configuración de la tabla
    # Cambiar el color del fondo a verde para los títulos de la tabla
    bcol_set(pdf, 'red')  # Establece el color verde para el fondo de las celdas
    tcol_set(pdf, 'white')
    pdf.set_font("Arial", "B", 12)

    # Dibujar las celdas de los títulos con fondo verde
    pdf.cell(33, 10, "Nombre", 1, 0, 'C', fill=True)
    pdf.cell(33, 10, "Apellido", 1, 0, 'C', fill=True)
    pdf.cell(30, 10, "DNI", 1, 0, 'C', fill=True)
    pdf.cell(30, 10, "Telefono", 1, 0, 'C', fill=True)
    pdf.cell(30, 10, "Salario", 1, 0, 'C', fill=True)
    pdf.cell(33, 10, "Fecha ingreso", 1, 1, 'C', fill=True)

    tcol_set(pdf, 'black')
    # Cambiar el estilo de fuente para el contenido
    pdf.set_font("Arial", "", 12)

    # Obtener todos los productos de la base de datos
    empleados = Empleado.objects.all()

    # Verificar si hay productos
    if empleados.exists():
        c = 0  # Contador para alternar el color de las filas
        for empleado in empleados:
            c += 1

            # Alternar el color de fondo entre gris y blanco
            if c % 2 == 0:
                bcol_set(pdf, 'gray2')  # Fila gris
            else:
                bcol_set(pdf, 'white')  # Fila blanca
            
            if empleado.estado=='activo':
                pdf.cell(33, 10, f"{empleado.nombre}", 1, 0, 'C', fill=True)
                pdf.cell(33, 10, f"{empleado.apellido}", 1, 0, 'C', fill=True)
                pdf.cell(30, 10, f"{empleado.dni}", 1, 0, 'C', fill=True)
                pdf.cell(30, 10, f"{empleado.telefono}", 1, 0, 'C', fill=True)
                pdf.cell(30, 10, f"${empleado.salario}", 1, 0, 'C', fill=True) 
                pdf.cell(33, 10, f"{empleado.fechaDeIngreso}", 1, 1, 'C', fill=True)
            else:
                c-=1
    else:
        pdf.cell(0, 10, "No hay productos disponibles.", 0, 1, 'C')

    # Preparar la respuesta
    response = HttpResponse(pdf.output(dest='S').encode('latin1'), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporteProductos.pdf"'
    return response

apps/usuarios/templates/usuarios/agregarEmpleado.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
    <div class="contenedor-agregarProd d-flex justify-content-center align-items-center">
        <div class="card-agregarProd" >
            <h3 class="text-center" style="color: #a63348;">Agregar un empleado</h3>
            <form method="POST" enctype="multipart/form-data">
                <form method="post">
                    {% csrf_token %}
                
                    <div class="mb-3">
                        {{ form.nombre.label_tag }} 
                        {{ form.nombre }}  
                    </div>
        
                    <div class="mb-3">
                        {{ form.apellido.label_tag }}
                        {{ form.apellido }}
                    </div>
                
                    <div class="mb-3">
                        {{ form.dni.label_tag }} 
                        {{ form.dni }}  
                    </div>
                    
                    <div class="mb-3">
                        {{ form.direccion.label_tag }} 
                        {{ form.direccion }} 
                    </div>

                    <div class="mb-3">
                        {{ form.telefono.label_tag }} 
                        {{ form.telefono }} 
                    </div>

                    <div class="mb-3">
                        {{ form.mail.label_tag }} 
                        {{ form.mail }} 
                    </div>

                    <div class="mb-3">
                        {{ form.fechaDeNacimiento.label_tag }} 
                        {{ form.fechaDeNacimiento }} 
                    </div>

                    <div class="mb-3">
                        {{ form.salario.label_tag }} 
                        {{ form.salario }} 
                    </div>

                    <div class="mb-3">
                        {{ form.fechaDeIngreso.label_tag }}  
                        {{ form.fechaDeIngreso }}  
                    </div>

                    <div class="mb-3">
                        {{ form.estado.label_tag }}  
                        {{ form.estado }}  
                    </div>

                    <div class="mb-3">
                        {{ form.user.label_tag }} 
                        {{ form.user }}
                        
                        <a href="{% url 'usuarios:crear_usuario' %}"><i class="fa-solid fa-plus" title="Crear usuario"></i></a>
                        
                    </div>
                
                
                <button type="submit" class="btn btn-addProd w-100 mt-3">Guardar empleado</button>
                <a href="{% url 'usuarios:empleados' %}" class="btn btn-cancelProd w-100 mt-2">Cancelar</a>
            </form>
        </div>
    </div>


{% endblock %}

{% block js %}

{% endblock %}

apps/usuarios/templates/usuarios/crear_usuario.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
    <h2>Crear Usuario</h2>
    
    <a href="{% url 'usuarios:agregarEmpleado' %}" class="btn btn-link">Cancelar</a>
    <div class="contenedor-agregarProd d-flex justify-content-center align-items-center">
        <div class="card-agregarProd">
            <h3 class="text-center" style="color: #a63348;">Agregar un empleado</h3>
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="text-danger">
                            {% for error in form.username.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.password1.label_tag }}
                    {{ form.password1 }}
                    {% if form.password1.errors %}
                        <div class="text-danger">
                            {% for error in form.password1.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.password2.label_tag }}
                    {{ form.password2 }}  
                    {% if form.password2.errors %}
                        <div class="text-danger">
                            {% for error in form.password2.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Crear Usuario</button>
            </form>    
        </div>
    </div>
{% endblock %}

apps/usuarios/templates/usuarios/edicionEmpleados.html
{%extends 'base/base.html'%}
{% load static %}

{% block contenido %}

<div class="contenedor-formProd d-flex justify-content-center">
    <div class="card-formProd">
        <form class="row g-3" id="form-prod" action="{% url 'usuarios:edicionEmpleado' %}" method="post" >{% csrf_token %}
            <h3 class="text-center" style="color: #a63348;">Editar Empleado</h3>
            <div class="col-12">
            <input type="hidden" name="id" value="{{ empleado.id }}">
            <label for="nombreEmpRegister" class="form-label"
                >Nombre</label
            >
            <div class="input-group">
                <input type="text" name="nombre" class="form-control" id="nombreEmpRegister" value="{{empleado.nombre}}" placeholder="Ingrese nombre del empleado" required/>
            </div>
            </div>
            <label for="nombreEmpRegister" class="labelTxt" id="nombreEmpLabel"></label>

            <div class="col-12">
            <label for="apellidoEmpRegister" class="form-label">Apellido</label>
            <div class="input-group">
                <input type="text" name="apellido" class="form-control" id="apellidoEmpRegister" value="{{ empleado.apellido }}" required/>
            </div>
            </div>
            <label for="apellidoEmpRegister" class="labelTxt" id="apellidoEmpLabel"></label>

            <div class="col-12">
                <label for="dniEmpRegister" class="form-label"
                >DNI</label>
                <div class="input-group">
                <input type="text" name="dni" class="form-control" id="dniEmpRegister" value="{{empleado.dni}}" required/>
                </div>
            </div>
            <label for="dniEmpRegister" class="labelTxt" id="dniEmpLabel"></label>

            <div class="col-12">
                <label for="direccionEmpRegister" class="form-label"
                >Dirección</label>
                <div class="input-group">
                <input type="text" name="direccion" class="form-control" id="direccionEmpRegister" value="{{empleado.direccion}}" required readonly/>
                </div>
            </div>
            <label for="direccionEmpRegister" class="labelTxt" id="direccionEmpLabel"></label>

            <div class="col-12">
                <label for="telefonoEmpRegister" class="form-label"
                >Teléfono</label>
                <div class="input-group">
                <input type="text" name="telefono" class="form-control" id="telefonoEmpRegister" value="{{empleado.telefono}}" required/>
                </div>
            </div>
            <label for="telefonoEmpRegister" class="labelTxt" id="telefonoEmpLabel"></label>

            <div class="col-12">
            <label for="emailEmpRegister" class="form-label">Email</label>
            <input type="email" name="mail" class="form-control" id="emailEmpRegister" value="{{empleado.mail}}" required/>
            </div>
            <label for="emailEmpRegister" class="labelTxt" id="emailEmpLabel"></label>

            <div class="col-12">
                <label for="fechaNacRegister" class="form-label">Fecha de Nacimiento</label>
                <input type="date" name="fechaDeNacimiento" class="form-control" id="fechaNacRegister" value="{{empleado.fechaDeNacimiento|date:'Y-m-d'}}" required/>
                </div>
                <label for="fechaNacRegister" class="labelTxt" id="fechaNacLabel"></label>

            <div class="col-12">
                <label for="salarioEmpRegister" class="form-label">Salario</label>
                <div class="input-group">
                <input type="number" step="0.01" name="salario" class="form-control" id="salarioEmpRegister" value="{{empleado.salario}}" required/>
                </div>
            </div>
            <label for="salarioEmpRegister" class="labelTxt" id="salarioEmpLabel"></label>

            <div class="col-12">
                <label for="usuarioEmpRegister" class="form-label">usuario</label>
                <div class="input-group">
                <input type="text" name="usuario" class="form-control" id="usuarioEmpRegister" value="{{empleado.user.username}}" required readonly/>
                </div>
            </div>
            <label for="usuarioEmpRegister" class="labelTxt" id="usuarioEmpLabel"></label>

            <div class="col-12">
                <label for="fechaIngresoRegister" class="form-label">Fecha de ingreso</label>
                <div class="input-group">
                <input type="date" name="fechaDeIngreso" class="form-control" id="fechaIngresoRegister" value="{{empleado.fechaDeIngreso|date:'Y-m-d'}}" required/>
                </div>
            </div>
            <label for="fechaIngresoRegister" class="labelTxt" id="fechaIngresoLabel"></label>

            <div class="col-12">
                <label for="estadoRegister" class="form-label">Estado</label>
                <div class="input-group">
                <select name="estado" id="estadoRegister" class="form-control">
                {%if empleado.estado == 'activo'%}
                    <option value="{{empleado.estado}}">{{empleado.estado}}</option>
                    <option value="inactivo">Inactivo</option>
                {%else%}
                    <option value="{{empleado.estado}}">{{empleado.estado}}</option>
                    <option value="activo">Activo</option>
                {% endif %}
                </select>
                </div>
            </div>
            <label for="estadoRegister" class="labelTxt" id="estadoLabel"></label>
            
            <div class="col-12">
                <button class="btn bg-primario w-100 mt-4" type="submit">Registrar</button>
                <button class="btn bg-secundario w-100 mt-1" type="reset">Restablecer valores</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
   <script src="{% static 'js/tratamientoFechas.js' %}"></script>
   <script>
    document.getElementById('salarioEmpRegister').addEventListener('input', function (event) {
        this.value = this.value.replace(/[^0-9.]/g, '');
    });
    
</script>
{% endblock %}    

apps/usuarios/templates/usuarios/empleados.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
<div class="container" id="container-tabla">
    <div class="col-12">
        <h2 class="text-center pb-3">Registro de empleados</h2>
        <div class="busqueda d-flex">
            <form class="d-flex align-items-center justify-content-center" role="search" method="POST" action="{% url 'usuarios:buscarEmpleado' %}">
                {% csrf_token %}
                <input class="form-control mb-3" type="search" placeholder="Buscar por DNI" aria-label="buscar" name="busqueda" value="{{ busqueda|default:'' }}" />
                <button class="btn" type="submit">
                    <i class="fa-solid fa-magnifying-glass" style="font-size: 16px"></i>
                </button>
                <a href="{% url 'usuarios:empleados' %}"><i class="fa-solid fa-rotate-left"></i></a>
            </form>
   
        <a href="{% url 'usuarios:agregarEmpleado' %}"><i class="fa-solid fa-square-plus" title="Agregar empleado" style="font-size: 30px"></i></a>
        <a class="expPdf" href="{% url 'usuarios:generarPDF' %}"><i class="fa-solid fa-file-pdf px-2" style="font-size: 25px"></i>Exportar PDF</a>
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead class="bg-table">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">DNI</th>
                        <th scope="col">Dirección</th>
                        <th scope="col">Teléfono</th>
                        <th scope="col">Email</th>
                        <th scope="col">Fecha de Nac.</th>
                        <th scope="col">Salario</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">Fecha Ingreso</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                        <tr class="{% if empleado.estado == 'inactivo' %}table-secondary{% endif %}">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ empleado.nombre }}</td>
                            <td>{{ empleado.apellido }}</td>
                            <td>{{ empleado.dni }}</td>
                            <td>{{ empleado.direccion }}</td>
                            <td>{{ empleado.telefono }}</td>
                            <td>{{ empleado.mail }}</td>
                            <td>{{ empleado.fechaDeNacimiento|date:"d/m/Y" }}</td>
                            <td>${{ empleado.salario }}</td>
                            <td>{{ empleado.user.username }}</td>
                            <td>{{ empleado.fechaDeIngreso|date:"d/m/Y" }}</td>
                            <td>{{ empleado.estado }}</td>
                            <td>
                                <a href="{% url 'usuarios:editarEmpleado' empleado.id%}"><i class="fa-solid fa-pen-to-square" title="Editar" data-bs-toggle="modal" data-bs-target="#exampleModal"></i></a>
                                <a href="{% url 'usuarios:eliminarEmpleado' empleado.id%}"><i class="fa-solid fa-trash-can" title="Eliminar" data-bs-toggle="modal" data-bs-target="#deleteModal"></i></a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="12">No hay productos disponibles.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}