Panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.inicio.urls')),
    path('productos/',include('apps.productos.urls')),
    path('',include('apps.pedidos.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('empleados/',include('apps.usuarios.urls')),
]

apps/ventas/urls.py
from django.urls import path
from . import views,views_mayoristas
from django.contrib.auth.decorators import login_required

app_name='ventas'

urlpatterns = [
    path('',login_required(views.ventas),name='ventas'),
    path('agregarVenta/',login_required(views.agregarVenta) ,name='agregarVenta'),
    path('verDetallesVenta/<venta_id>',login_required(views.verDetallesVenta),name='verDetallesVenta'),
    path('buscarVentas/',login_required(views.buscarVentas),name='buscarVentas'),
    path('exportarPDF/',login_required(views.exportarPDF),name='exportarPDF'),
    path('listadoMayoristas/',login_required(views_mayoristas.listadoMayoristas),name='listadoMayoristas'),
    path('agregarMayorista/',login_required(views_mayoristas.agregarMayorista),name='agregarMayorista'),
    path('editarMayorista/<mayorista_id>',login_required(views_mayoristas.editarMayorista),name='editarMayorista'),
    path('edicionMayorista/',login_required(views_mayoristas.edicionMayorista),name='edicionMayorista'),
    path('buscarMayorista/',login_required(views_mayoristas.buscarMayorista),name='buscarMayorista'),
    path('exportarPDF_Mayoristas/',login_required(views_mayoristas.exportarPDF_Mayoristas),name='exportarPDF_Mayoristas'),
    path('obtener-precio-producto/<producto_id>/', login_required(views.obtener_precio_producto), name='obtener_precio_producto'),
    path('exportarPDF_ProductosMasVendidos',login_required(views.exportarPDF_ProductosMasVendidos),name='exportarPDF_ProductosMasVendidos'),
] 

#Ver tema de permisos con los empleados

apps/ventas/models.py
from django.db import models
from apps.usuarios.models import Persona, Empleado
from apps.productos.models import Producto
from decimal import Decimal
# Create your models here.

class ClienteMayorista(Persona):
    cuil = models.CharField(max_length=13,blank=False, null=False)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.cuil}"

class Venta(models.Model):
    TIPO_COMPROBANTE = [
        ('A', 'Factura A'),
        ('B', 'Factura B'),
        ('C', 'Factura C'),
    ]
    FORMA_PAGO = [
        ('efectivo','Efectivo'),
        ('transferencia','Transferencia'),
        ('débito','Débito'),
        ('crédito','Crédito'),
    ]
    fechaDeVenta = models.DateField(blank=False, null=False)
    formaDePago = models.CharField(max_length=15, choices=FORMA_PAGO,blank=False, null=False)
    tipoDeComprobante = models.CharField(max_length=15, choices=TIPO_COMPROBANTE,blank=False, null=False)
    clienteMayorista = models.ForeignKey(ClienteMayorista, on_delete=models.SET_NULL, null=True, blank=True,related_name='clienteMayorista')
    total = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name='ventaEmpleado')
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Guarda primero la instancia
    
    def calcular_total(self):
        # Calcula el total de todos los detalles de la venta
        self.total = sum(detalle.subTotal for detalle in self.detalleVenta.all())
        self.save(update_fields=['total'])  # Guarda solo el campo total
    
    def __str__(self):
        if self.clienteMayorista is None:
            return f"Venta a consumidor final - {self.fechaDeVenta}"
        else:
            return f"Venta a mayorista {self.clienteMayorista.nombre} - {self.fechaDeVenta}"

class DetalleVenta(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE,related_name='detalleProducto')
    venta = models.ForeignKey(Venta,on_delete=models.CASCADE,related_name='detalleVenta')
    cantidad = models.DecimalField(max_digits=10, decimal_places=2,blank=False, null=False)
    subTotal = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    
    def save(self, *args, **kwargs):
        self.subTotal = self.cantidad * self.producto.precioDeVenta
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.producto.nombre} {self.cantidad} {self.subTotal}"
    

apps/ventas/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from .models import ClienteMayorista, Venta,DetalleVenta

class FormularioVenta(forms.ModelForm):
    class Meta:
        model = Venta
        fields = [
            'fechaDeVenta', 
            'formaDePago', 
            'tipoDeComprobante', 
            'clienteMayorista', 
            
        ]
        labels = {
            'fechaDeVenta': 'Fecha de venta',
            'formaDePago': 'Forma de pago',
            'tipoDeComprobante': 'Tipo de comprobante',
            'clienteMayorista': 'Cliente mayorista',
        }  
        widgets = {
            'fechaDeVenta': forms.TextInput(attrs={'type': 'date','class': 'form-control'}),
            'formaDePago': forms.Select(attrs={'class': 'form-control'}),
            'tipoDeComprobante': forms.Select(attrs={'class': 'form-control'}),
            'clienteMayorista': forms.Select(attrs={'type': 'date','class': 'form-control'}),
        }
        
class DetalleVentaForm(forms.ModelForm):
    class Meta:
        model = DetalleVenta
        fields = ['producto', 'cantidad']
        labels = {
            'producto': 'Producto',
            'cantidad': 'Cantidad',
        }
        widgets = {
            'producto': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control','step': '0.01'}),
        }
    
    def clean_cantidad(self):
        cantidad = self.cleaned_data.get('cantidad')
        producto = self.cleaned_data.get('producto')
        
        if cantidad > producto.cantidadDisponible:
            raise forms.ValidationError(f"Solo hay {producto.cantidadDisponible} unidades disponibles de {producto.nombre}.")
        
        return cantidad

DetalleVentaFormSet = inlineformset_factory(
    Venta, 
    DetalleVenta,  # Venta y DetalleVenta son los modelos relacionados
    form=DetalleVentaForm,
    extra=1,  # comienza mostrando 1 formulario
    can_delete=True  # permite borrar el formulario
)

class FormularioMayorista(forms.ModelForm):
    class Meta:
        model = ClienteMayorista
        fields = ['nombre', 'apellido','cuil', 'direccion','telefono', 'mail']
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'cuil': 'CUIL',
            'direccion': 'Dirección',
            'telefono': 'Teléfono',
            'mail': 'Email',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'cuil': forms.TextInput(attrs={'class': 'form-control','maxlength': '13'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'mail': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/ventas/views.py
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from apps.ventas.models import Venta,DetalleVenta
from apps.ventas.forms import FormularioVenta,DetalleVentaFormSet
from apps.usuarios.models import Empleado
from fpdf import FPDF
from datetime import datetime
import os
from django.http import HttpResponse,JsonResponse
from apps.productos.models import Producto
from django.db.models import Sum

def ventas(request):
    ventas = Venta.objects.all()
    return render(request,'ventas/ventas.html',{'ventas':ventas})

def agregarVenta(request):
    if request.method == 'POST':
        ventaForm = FormularioVenta(request.POST)
        detalleVentaFormset = DetalleVentaFormSet(request.POST)
        
        if ventaForm.is_valid() and detalleVentaFormset.is_valid():

            empleado = get_object_or_404(Empleado, user=request.user)
            venta = ventaForm.save(commit=False)  # No guardar todavía la venta
            venta.empleado = empleado  
            venta.save()  
            totalVenta = 0
            detalles = detalleVentaFormset.save(commit=False) # No guardar todavía los detalles
            
            for detalle in detalles: 
                detalle.venta = venta
                detalle.subTotal = detalle.cantidad * detalle.producto.precioDeVenta
                totalVenta += detalle.subTotal
                producto = detalle.producto
                producto.cantidadDisponible -= detalle.cantidad
                producto.save() #acá vamos a actualizar la cantidad disponible de cada producto cuando se realice una venta
                detalle.save()  #acá guardamos cada detalle de venta
            
            venta.total = totalVenta
            venta.save() #acá se actualiza la venta con todos los detalles de venta y se actualiza el precio total de la venta
            return redirect('/ventas')
    else:
        ventaForm = FormularioVenta()
        detalleVentaFormset = DetalleVentaFormSet()

    return render(request, 'ventas/agregarVenta.html', {'ventaForm': ventaForm,'detalleVentaFormset': detalleVentaFormset,})


def verDetallesVenta(request,venta_id):
    detallesVenta = DetalleVenta.objects.filter(venta_id=venta_id)
    venta = Venta.objects.get(id=venta_id)
    return render(request,'ventas/verDetallesVenta.html',{'detallesVenta':detallesVenta,'venta_id':venta_id,'venta':venta})
    

from django.shortcuts import render
from .models import ClienteMayorista, Venta

def buscarVentas(request):
    ventas = Venta.objects.all()
    fecha_inicio = request.POST.get('fecha_inicio')
    fecha_fin = request.POST.get('fecha_fin')

    # Lógica de filtrado
    if fecha_inicio and fecha_fin:
        # Filtra por rango de fechas
        ventas = ventas.filter(fechaDeVenta__range=[fecha_inicio, fecha_fin])
    elif fecha_inicio:
        # Si solo se ingresa fecha de inicio, filtra por esa fecha exacta
        ventas = ventas.filter(fechaDeVenta=fecha_inicio)
    else:
        return redirect('/ventas')

    return render(request, 'ventas/ventas.html', {'ventas': ventas, 'fecha_inicio': fecha_inicio, 'fecha_fin': fecha_fin})



def diccionario_colores(color): 
    colores = {
        'black' : (0,0,0), 
        'white' : (255,255,255),
        'green' : (96,218,117),
        'blue' : (96,181,218),
        'red': (119,30,48),
        'rose': (214,74,236),
        'gray': (103,103,103),
        'gray2': (233,233,233),
    }
    return colores[color]

def dcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_draw_color(r= cr, g = cg, b= cb)

def bcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_fill_color(r= cr, g = cg, b= cb)

def tcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_text_color(r= cr, g = cg, b= cb)

def tfont_size(hoja, size):
    hoja.set_font_size(size)

def tfont(hoja, estilo, fuente='Arial'):
    hoja.set_font(fuente, style=estilo)

class PDF(FPDF):
    def __init__(self, title):
        super().__init__()
        self.title = title
    
    def header(self):
        logo = os.path.join(settings.BASE_DIR, 'static', 'img', 'logotipo.png')
        
        # Verificar si el archivo existe
        if os.path.exists(logo):
            self.image(logo, x=10, y=10, w=30, h=30) 
        
        self.set_font('Arial', '', 15)

        tcol_set(self, 'red')
        tfont_size(self,30)
        tfont(self,'B')
        self.cell(w = 0, h = 20, txt = self.title, border = 0, ln=1,
                align = 'C', fill = 0)

        tfont_size(self,10)
        tcol_set(self, 'black')
        tfont(self,'I')
        self.cell(w = 0, h = 10, txt = f'Generado el {datetime.now().strftime("%d/%m/%y")}', border = 0, ln=2,
                align = 'C', fill = 0)

        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 12)
        self.cell(w = 0, h = 10, txt =  'Pagina ' + str(self.page_no()),
                 border = 0,align = 'C', fill = 0)

def exportarPDF(request):
    pdf = PDF('Registro de ventas')
    pdf.add_page()
    
    # Configuración de la tabla
    bcol_set(pdf, 'red')  # Fondo rojo para los títulos de la tabla
    tcol_set(pdf, 'white')
    pdf.set_font("Arial", "B", 12)

    # Dibujar las celdas de los títulos con fondo rojo
    pdf.cell(35, 10, "Fecha de Venta", 1, 0, 'C', fill=True)
    pdf.cell(35, 10, "Forma de pago", 1, 0, 'C', fill=True)
    pdf.cell(25, 10, "Factura", 1, 0, 'C', fill=True)
    pdf.cell(40, 10, "Cliente", 1, 0, 'C', fill=True)
    pdf.cell(25, 10, "Total", 1, 0, 'C', fill=True)
    pdf.cell(30, 10, "Empleado", 1, 1, 'C', fill=True)

    tcol_set(pdf, 'black')
    pdf.set_font("Arial", "", 12)

    ventas = Venta.objects.all()

    if ventas.exists():
        c = 0  # Contador para alternar el color de las filas
        for venta in ventas:
            c += 1

            # Alternar el color de fondo entre gris y blanco
            if c % 2 == 0:
                bcol_set(pdf, 'gray2')  # Fila gris
            else:
                bcol_set(pdf, 'white')  # Fila blanca
            
            # Dibujar las celdas con el color de fondo establecido
            fechaVenta = venta.fechaDeVenta.strftime('%Y-%m-%d')
            pdf.cell(35, 10, fechaVenta, 1, 0, 'C', fill=True)
            pdf.cell(35, 10, f"{venta.formaDePago}", 1, 0, 'C', fill=True)  # Sin `.2f`
            pdf.cell(25, 10, f"{venta.tipoDeComprobante}", 1, 0, 'C', fill=True)
            if venta.clienteMayorista is None:
               pdf.cell(40, 10, "Consumidor Final", 1, 0, 'C', fill=True)
            else:
                pdf.cell(40, 10, f"{venta.clienteMayorista.cuil}", 1, 0, 'C', fill=True)
            pdf.cell(25, 10, f"${venta.total:.2f}", 1, 0, 'C', fill=True)  # Con `.2f` para el total decimal
            pdf.cell(30, 10, f"{venta.empleado.dni}", 1, 1, 'C', fill=True)
    else:
        pdf.cell(0, 10, "No hay productos disponibles.", 0, 1, 'C')

    response = HttpResponse(pdf.output(dest='S').encode('latin1'), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporteVenta.pdf"'
    return response

def obtener_precio_producto(request, producto_id):
    try:
        producto = Producto.objects.get(id=producto_id)
        return JsonResponse({'precio': str(producto.precioDeVenta)})
    except Producto.DoesNotExist:
        return JsonResponse({'error': 'Producto no encontrado'}, status=404)


from django.db.models import Sum
from django.http import HttpResponse

def exportarPDF_ProductosMasVendidos(request):
    pdf = PDF('Productos más vendidos')
    pdf.add_page()
    
    bcol_set(pdf, 'red') 
    tcol_set(pdf, 'white')
    pdf.set_font("Arial", "B", 12)

    pdf.cell(50, 10, "Nombre de producto", 1, 0, 'C', fill=True)
    pdf.cell(50, 10, "Cantidad Vendida", 1, 0, 'C', fill=True)
    pdf.cell(40, 10, "Unidad de medida", 1, 0, 'C', fill=True)
    pdf.cell(50, 10, "Total Vendido", 1, 1, 'C', fill=True)

    # Consulta para obtener productos más vendidos con el total calculado usando el subtotal
    productos_vendidos = (
        DetalleVenta.objects
        .values('producto__nombre', 'producto__unidadDeMedida')
        .annotate(total_vendido=Sum('cantidad'), total_subtotal=Sum('subTotal'))
        .order_by('-total_vendido')
    )

    tcol_set(pdf, 'black')
    pdf.set_font("Arial", "", 12)

    if productos_vendidos:
        for idx, producto in enumerate(productos_vendidos):
            if idx % 2 == 0:
                bcol_set(pdf, 'gray2')  
            else:
                bcol_set(pdf, 'white')  
                
            pdf.cell(50, 10, producto['producto__nombre'], 1, 0, 'C', fill=True)
            pdf.cell(50, 10, f"{producto['total_vendido']:.2f}", 1, 0, 'C', fill=True)
            pdf.cell(40, 10, producto['producto__unidadDeMedida'], 1, 0, 'C', fill=True)
            pdf.cell(50, 10, f"${producto['total_subtotal']:.2f}", 1, 1, 'C', fill=True)
    else:
        pdf.cell(0, 10, "No hay productos disponibles.", 0, 1, 'C')

    response = HttpResponse(pdf.output(dest='S').encode('latin1'), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporteProductosMasVendidos.pdf"'
    return response


    

apps/ventas/templates/ventas/agregarVenta.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
    <div class="contenedor-agregarVenta d-flex justify-content-center align-items-center">
        <div class="card-agregarVenta">
            <h3 class="text-center" style="color: #a63348;">Agregar una venta</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ ventaForm.as_p }}

                <h3>Detalles de Venta</h3>
                {{ detalleVentaFormset.management_form }}
                
                <!-- Contenedor para los detalles de venta -->
                <div id="detalleVentaContainer">
                    {% for form in detalleVentaFormset %}
                        <div class="detalle-form">
                            {{ form.as_p }}
                            <h5 class="subtotal" id="detalleVenta-{{ forloop.counter0 }}-subtotal">Subtotal: $<span id="id_producto-{{ forloop.counter0 }}-precio"></span></h5>
                        </div>
                    {% endfor %}
                </div>
                <button type="button" class="btn btn-secondary mt-3" id="btn-addProd">Agregar producto</button>
                <div class="d-flex justify-content-end">
                    <h4 class="total">Total: $<span id="id_total_ventas"></span></h4>
                </div>
                <button type="submit" class="btn btn-addVenta w-100 mt-3">Guardar Venta</button>
                <a href="{% url 'ventas:ventas' %}" class="btn btn-cancelProd w-100 mt-2">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
        const formsetContainer = document.getElementById('detalleVentaContainer');
        const totalForms = document.getElementById('id_detalleVenta-TOTAL_FORMS');
        const ElementoTotal = document.getElementById('id_total_ventas');

        // Función para agregar un nuevo formulario de detalle de venta
        document.getElementById('btn-addProd').addEventListener('click', function() {
            if (totalForms) {
                const contadorForm = parseInt(totalForms.value);
                const nuevoForm = formsetContainer.children[contadorForm - 1].cloneNode(true);

                // Limpiar valores de los inputs en el formulario clonado
                const inputs = nuevoForm.getElementsByTagName('input');
                for (let input of inputs) {
                    input.value = '';
                }

                // Actualizar los nombres y IDs de los campos del nuevo formulario
                nuevoForm.querySelectorAll('input, select').forEach((element) => {
                    element.name = element.name.replace(/-\d+-/, `-${contadorForm}-`);
                    element.id = element.id.replace(/-\d+-/, `-${contadorForm}-`);
                });

                const subtotalSpan = nuevoForm.querySelector('.subtotal span');
                subtotalSpan.id = `id_producto-${contadorForm}-precio`;

                // Incrementar el contador de formularios y agregar el nuevo formulario al contenedor
                totalForms.value = contadorForm + 1;
                formsetContainer.appendChild(nuevoForm);

                // Agregar el evento para calcular subtotal y total al nuevo formulario
                agregarEventosFormulario(contadorForm);
            } else {
                console.error('El elemento TOTAL_FORMS no se encuentra en el DOM.');
            }
        });

        // Función para agregar eventos de cálculo a cada formulario de detalle de venta
        function agregarEventosFormulario(formIndex) {
            const productoSelect = document.getElementById(`id_detalleVenta-${formIndex}-producto`);
            const cantidadProducto = document.getElementById(`id_detalleVenta-${formIndex}-cantidad`);
            const productoPrecio = document.getElementById(`id_producto-${formIndex}-precio`);

            if (productoSelect && cantidadProducto && productoPrecio) {
                // Escuchar cambios en el campo de cantidad y en el producto seleccionado
                productoSelect.addEventListener('change', actualizarSubtotal);
                cantidadProducto.addEventListener('input', actualizarSubtotal);

                function actualizarSubtotal() {
                    const productoId = productoSelect.value;
                    const cantidad = parseFloat(cantidadProducto.value) || 0;

                    if (productoId) {
                        fetch(`/ventas/obtener-precio-producto/${productoId}/`)
                            .then(response => response.json())
                            .then(data => {
                                if (data.precio) {
                                    let subtotal = data.precio * cantidad;
                                    productoPrecio.textContent = subtotal.toFixed(2); // Mostrar subtotal formateado

                                    // Actualizar el total general de todos los subtotales
                                    actualizarTotal();
                                } else {
                                    productoPrecio.textContent = '0';
                                    actualizarTotal();
                                    alert(data.error || 'Error al obtener el precio');
                                }
                            })
                            .catch(error => console.error('Error:', error));
                    } else {
                        productoPrecio.textContent = '';
                        actualizarTotal();
                    }
                }
            } else {
                console.error(`Elementos del formulario de índice ${formIndex} no encontrados.`);
            }
        }

        // Función para actualizar el total general
        function actualizarTotal() {
            let totalVenta = 0;

            // Sumar subtotales de cada producto
            document.querySelectorAll('h5.subtotal span[id^="id_producto-"][id$="-precio"]').forEach((span) => {
                const subtotal = parseFloat(span.textContent) || 0;
                totalVenta += subtotal;
            });

            if (ElementoTotal) {
                ElementoTotal.textContent = totalVenta.toFixed(2); // Mostrar el total formateado
            } else {
                console.error('Elemento de total no encontrado en el DOM.');
            }
        }

        // Agregar eventos al formulario inicial
        if (totalForms) {
            for (let i = 0; i < parseInt(totalForms.value); i++) {
                agregarEventosFormulario(i);
            }
        } else {
            console.error('Elemento TOTAL_FORMS no encontrado en el DOM.');
        }
    });

</script>
<script src="{% static 'js/tratamientoFechas.js'%}"></script>
{% endblock %}

apps/ventas/templates/ventas/ventas.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
<div class="container" id="container-tabla">
    <div class="col-12">
        <h2 class="text-center pb-3">Registro de ventas</h2>
        <div class="busqueda d-flex justify-content-between align-items-center">
            <form class="d-flex align-items-center" role="search" method="POST" action="{% url 'ventas:buscarVentas' %}">
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <label for="fecha_inicio" class="me-1">Fecha de inicio:</label>
                            <input type="date" id="fecha_inicio" name="fecha_inicio" class="form-control busquedaFecha d-inline" placeholder="inicio" style="width: 150px;">
                            <label for="fecha_fin" class="ms-2 me-1">Fecha de fin:</label>
                            <input type="date" id="fecha_fin" name="fecha_fin" class="form-control busquedaFecha d-inline" style="width: 150px;">
                        </div>
                        <div class="col">
                            <button class="btn" type="submit">
                                <i class="fa-solid fa-magnifying-glass" style="font-size: 16px"></i>
                            </button>
                            <a href="{% url 'ventas:ventas' %}" class="ms-2"><i class="fa-solid fa-rotate-left"></i></a> 
                        </div>  
                    </div>
                </div>
            </form>
            <a href="{% url 'ventas:agregarVenta' %}"><i class="fa-solid fa-square-plus" title="Agregar venta" style="font-size: 30px"></i></a>
            <a class="expPdf" href="#" data-bs-toggle="modal" data-bs-target="#pdfModal"><i class="fa-solid fa-file-pdf px-2" style="font-size: 25px"></i>Exportar PDF</a>
        </div>
        
        
        
    
        <div class="table-responsive">
            <table class="table">
                <thead class="bg-table">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Fecha de venta</th>
                        <th scope="col">Forma de pago</th>
                        <th scope="col">Tipo de comprobante</th>
                        <th scope="col">Cliente mayorista</th>
                        <th scope="col">Total</th>
                        <th scope="col">Empleado</th>
                        <th scope="col">Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for venta in ventas %} 
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ venta.fechaDeVenta|date:"d/m/Y" }}</td>
                        <td>{{ venta.formaDePago }}</td>
                        <td>Factura {{ venta.tipoDeComprobante }}</td>
                        {% if venta.clienteMayorista is None %}
                            <td>Consumidor final</td>
                        {% else %}
                            <td>{{ venta.clienteMayorista.cuil }}</td>
                        {%endif%}
                        <td>${{ venta.total }}</td>
                        <td>{{ venta.empleado.nombre }} {{ venta.empleado.apellido }}</td>
                        <td>
                            <a href="{% url 'ventas:verDetallesVenta' venta.id %}"><i class="fa-solid fa-eye" title="Ver detalles"></i></a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="10">No hay ventas disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="pdfModal" tabindex="-1" aria-labelledby="pdfModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pdfModalLabel">Seleccione el tipo de reporte</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Elija el tipo de reporte que desea exportar en PDF:</p>
                <a href="{% url 'ventas:exportarPDF' %}" class="btn btn-addProd text-center">Todas las ventas</a>
                <a href="{% url 'ventas:exportarPDF_ProductosMasVendidos' %}" class="btn btn-addProd text-center">Productos más vendidos</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/tratamientoFechas.js'%}"></script>
{% endblock %}