Panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.inicio.urls')),
    path('productos/',include('apps.productos.urls')),
    path('',include('apps.pedidos.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('empleados/',include('apps.usuarios.urls')),
]

apps/pedidos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name='pedidos'

urlpatterns = [
    path('proveedores/',login_required(views.proveedores),name='proveedores'),
    path('proveedores/editar/<proveedor_id>',login_required(views.editarProveedor),name='editarProveedor'), #mandar plantilla del prov a editar
    path('proveedores/eliminar/<proveedor_id>',login_required(views.eliminarProveedor),name='eliminarProveedor'),
    path('proveedores/edicion/',login_required(views.edicionProveedor),name='edicionProveedor'),
    path('proveedores/buscar/', login_required(views.buscarProveedor), name='buscarProveedor'),
    path('proveedores/buscar/editar/<proveedor_id>',login_required(views.editarProveedor),name='editarProveedorBuscado'),
    path('proveedores/buscar/eliminar/<proveedor_id>',login_required(views.eliminarProveedor),name='eliminarProveedorBuscado'),
    path('proveedores/generarPDF/', login_required(views.generarPDF), name='generarPDF'),
    
    path('pedidos/',login_required(views.pedidos),name='pedidos'),
    path('pedidos/verDetallesPedido/<pedido_id>',login_required(views.verDetallePedido),name='verDetallePedido'),
    path('pedidos/buscar/', login_required(views.buscarPedidoPorFecha), name='buscarPorFecha'),
    path('pedidos/buscar/generarPDF/', login_required(views.generarPDFPedidos), name='generarPDFPedidos'),
    path('pedidos/generarPDF/', login_required(views.generarPDFPedidosConfirmados), name='generarPDFPedConfir'),
    path('pedidos/<pedido_id>/<str:caracter>/',login_required(views.actualizarEstadoPedido),name='actualizarPedido'),
    path('obtener-precio-insumo/<insumo_id>/', login_required(views.obtener_precio_Insumo), name='obtener_precio_insumo'), #fetch para el subtotal
    
    path('pedidos/recepcionPedido/<pedido_id>',login_required(views.recepcionPedido),name='recepcionDePedido'),
    path('pedidos/recepcionPedido/<pedido_id>/generarPDF/',login_required(views.generarPDFRecepPedido),name='generarPDFrecepcion'),
    path('pedidos/recepcionPedido/verDetallesPedido/<pedido_id>',login_required(views.verDetallePedido),name='verDetallePedidoDesdeRecepcion'),
    path('pedidos/recepcionPedido/verDetallesRecepcion/<pedido_id>',login_required(views.verDetallesRecepcionPedido),name='verDetallesRecepcionPedido'),

]

apps/pedidos/models.py
from django.db import models
from apps.productos.models import Insumo
from apps.usuarios.models import Persona,Empleado

# Create your models here.

class Proveedor(Persona):
    ESTADO = [
        ('activo', 'Activo'), 
        ('inactivo', 'Inactivo'),
    ]
    dni  = models.CharField(max_length=8,blank=False,null=False)
    estado = models.CharField(max_length=10, choices=ESTADO,blank=False, null=False)
    empresa = models.CharField(max_length=50,blank=False,null=False)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.dni}" 

class Pedido(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE,related_name = 'proveedor')
    ESTADO_PEDIDO = [
        ('confirmado', 'Confirmado'),
        ('pendiente', 'Pendiente'),
        ('cancelado', 'Cancelado'),
    ]
    fechaPedido = models.DateField(blank=False,null=False)
    estadoPedido = models.CharField(max_length=10,choices=ESTADO_PEDIDO,blank=False,null=False)
    precioTotalDelPedido = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=0)
    
    def __str__(self):
        return f"{self.fechaPedido} {self.estadoPedido}"
    
class DetallePedido(models.Model):
    pedido = models.ForeignKey(Pedido,null=True, on_delete=models.CASCADE, related_name='detalles')
    insumos = models.ForeignKey(Insumo,on_delete=models.CASCADE,related_name='insumos')
    cantidadPedida = models.PositiveIntegerField(blank=False,null=False)
    observaciones = models.TextField(null=True, blank=True)
    subTotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        # Calcular el subtotal basado en la cantidad y el precio del insumo
        self.subTotal = self.cantidadPedida * self.insumos.precioInsumo  # Asegúrate de que Insumo tenga un campo `precio`
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"Detalle {self.id} - Insumo: {self.insumos} - Cantidad: {self.cantidadPedida}" 
    
class RecepcionPedido(models.Model):
    empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name='empleado')
    fechaDeRecepcion = models.DateField(blank=False,null=False)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='recepciones', null=True)
    
    def __str__(self):
        return f"{self.empleado.nombre} {self.empleado.apellido} {self.fechaDeRecepcion}"
    
class DetalleRecepcionPedido(models.Model):
    recepcionPedido = models.ForeignKey(RecepcionPedido, on_delete=models.CASCADE, related_name='detalleRecepcionPedido', null=True)
    detallePedido = models.ForeignKey(DetallePedido,on_delete=models.CASCADE,related_name='detalleRecepcionPedido')
    ESTADO = [
        ('completo','Completo'),
        ('incompleto','Incompleto'),
        ('erroneo','Erroneo'),
    ]
    cantidadRecibida = models.PositiveBigIntegerField(blank=False, null=False, default=0)
    estado = models.CharField(max_length=10,choices=ESTADO,blank=False,null=False)
    
    def __str__(self):
        return f"{self.detallePedido.insumos.nombre} {self.cantidadRecibida}"
    

    

apps/pedidos/views.py
import os
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from apps.pedidos.models import Proveedor, Pedido, DetallePedido, RecepcionPedido, DetalleRecepcionPedido
from apps.productos.models import Insumo
from apps.usuarios.models import Empleado
from apps.pedidos.forms import FormularioProveedor, FormularioPedido, DetallePedidoFormSet, FormularioRecepcionPedido,DetalleRecepcionPedidoForm
from fpdf import FPDF
from django.conf import settings
from datetime import datetime
from django.http import HttpResponse, JsonResponse

#-------------------------------------PROVEEDORES----------------------------------------------------------
@login_required
def proveedores(request):
    proveedores = Proveedor.objects.all()
    form = FormularioProveedor()
    mostrar_boton = True # Por defecto, mostramos el botón
    
    if request.method == 'POST':  # Si el formulario fue enviado
        form = FormularioProveedor(request.POST)
        if form.is_valid():
            form.save()  # Guarda el nuevo proveedor en la base de datos
            return redirect('/proveedores') # Redirige a la misma página para actualizar la lista de proveedores
        
    if request.path == '/proveedores/buscar/':
        mostrar_boton = False
        
    return render(request, 'proveedor/proveedores.html', {'proveedores': proveedores, 'form': form,'mostrar_boton': mostrar_boton})

def editarProveedor(request,proveedor_id): #Pasar el proveedor a la plantilla edicionProveedor
    proveedor = Proveedor.objects.get(id=proveedor_id)
    return render(request,'proveedor/edicionProveedor.html',{'proveedor':proveedor})

def edicionProveedor(request):
    if request.method == 'POST':  
        proveedor_id = request.POST.get('id')  # Asegúrate de obtener el ID
        proveedor = Proveedor.objects.get(id=proveedor_id)
        proveedor.nombre = request.POST['nombre']
        proveedor.apellido = request.POST['apellido']
        proveedor.dni = request.POST['dni']
        proveedor.direccion = request.POST['direccion']
        proveedor.telefono = request.POST['telefono']
        proveedor.mail = request.POST['mail']
        proveedor.estado = request.POST['estado']
        proveedor.empresa = request.POST['empresa']
        proveedor.save()  # Guarda los cambios en la base de datos
        
    return redirect('/proveedores')  # En caso de que no sea un POST, redirige

def eliminarProveedor(request,proveedor_id):
    proveedor = Proveedor.objects.get(id=proveedor_id)
    proveedor.delete()
    return redirect('/proveedores')

# 
def buscarProveedor(request):
    busqueda = request.POST['busqueda']  # Obtiene el término de búsqueda de la query
    proveedor = Proveedor.objects.all()  # Obtiene todos los productos por defecto

    if busqueda:  # Si hay un término de búsqueda
        proveedor = proveedor.filter(dni__icontains=busqueda)  # Filtra los productos por nombre

    return render(request, 'proveedor/proveedores.html', {'proveedores': proveedor, 'busqueda': busqueda})

#---------------------------------------PEDIDOS--------------------------------------------------------
def pedidos(request):
    pedidos = Pedido.objects.all()  # Obtener todos los pedidos
    mostrar_boton = True  # Variable para controlar la visibilidad del botón
    mostrar_botonPdf = False
    # Obtener todos los insumos y sus precios
    insumos_dict = {insumo.id: insumo.precioInsumo for insumo in Insumo.objects.all()}

    if request.method == 'POST':
        pedidoForm = FormularioPedido(request.POST)
        detallePedidoFormset = DetallePedidoFormSet(request.POST)

        if pedidoForm.is_valid() and detallePedidoFormset.is_valid():
            detalles_validos = False
            totalPedido = 0

            # Verificar si hay al menos un detalle válido
            for detalle_form in detallePedidoFormset:
                if not detalle_form.cleaned_data.get('DELETE') and detalle_form.is_valid():
                    detalles_validos = True
                    break
            
            if detalles_validos:
                # Guarda el pedido primero
                pedido = pedidoForm.save()  # Guarda el pedido y obtiene un ID
                
                for detalle_form in detallePedidoFormset:
                    if detalle_form.cleaned_data.get('DELETE'):
                        continue
                    if detalle_form.is_valid():
                        detalle = detalle_form.save(commit=False)  # No guarda aún
                        detalle.pedido = pedido  # Asigna el pedido a cada detalle
                        detalle.save()  # Ahora guarda el detalle
                        totalPedido += detalle.subTotal  # Suma el subtotal

                # Actualiza el total del pedido y guarda
                pedido.precioTotalDelPedido = totalPedido
                pedido.save()  # Guarda el pedido actualizado
                messages.success(request, f'Pedido creado correctamente. Número de pedido: {pedido.id}')
                return redirect('/pedidos')
            else:
                pedidoForm.add_error(None, "Se debe agregar al menos un detalle al pedido.")
    else:
        pedidoForm = FormularioPedido()  # Crear un nuevo formulario vacío
        detallePedidoFormset = DetallePedidoFormSet()  # Crear un nuevo formset vacío

    # Renderizar la plantilla con los formularios
    return render(request, 'pedido/pedidos.html', {
        'pedidoForm': pedidoForm,
        'detallePedidoFormset': detallePedidoFormset,
        'pedidos': pedidos,
        'mostrar_boton': mostrar_boton,
        'mostrar_botonPdf': mostrar_botonPdf,
        'insumos_dict': insumos_dict,  # Pasar los precios de los insumos
    })
    
def verDetallePedido(request,pedido_id):
    detallesPedido = DetallePedido.objects.filter(pedido_id=pedido_id)
    pedido = Pedido.objects.get(id=pedido_id)

    # Verificando desde dónde se accedió a esta vista
    if request.path.startswith('/pedidos/recepcionPedido/verDetallesPedido/'):
        url_retorno = f'/pedidos/recepcionPedido/{pedido_id}'
    elif 'url_retorno' in request.session:
        url_retorno = request.session['url_retorno']  # Usa la URL de búsqueda almacenada
        del request.session['url_retorno']
    else:
        url_retorno = '/pedidos/'

    return render(request, 'pedido/verDetallePedido.html', {
        'detallesPedido': detallesPedido,
        'pedido_id': pedido_id,
        'pedido': pedido,
        'url_retorno': url_retorno
    })

def buscarPedidoPorFecha(request):
    busqueda_fecha = request.session.get('busqueda_fecha', None)
    busqueda_numero = request.session.get('busqueda_numero', None)
    mostrar_botonPdf = True
    pedidos = Pedido.objects.all()  # Obtiene todos los pedidos por defecto

    # Si se hace una solicitud POST, actualiza los criterios de búsqueda desde el formulario
    if request.method == 'POST':
        busqueda_fecha = request.POST.get('busqueda_fecha')
        busqueda_numero = request.POST.get('busqueda_numero')
        
        # Guarda la URL completa de búsqueda en la sesión para el retorno
        request.session['url_retorno'] = request.get_full_path()
        
        # Actualiza los criterios de búsqueda en la sesión
        request.session['busqueda_fecha'] = busqueda_fecha
        request.session['busqueda_numero'] = busqueda_numero

    # Realiza el filtrado solo si hay términos de búsqueda
    if busqueda_fecha or busqueda_numero:
        try:
            # Filtra por fecha si se proporciona
            if busqueda_fecha:
                pedidos = pedidos.filter(fechaPedido=busqueda_fecha)
            
            # Filtra por número de pedido si se proporciona
            if busqueda_numero:
                pedidos = pedidos.filter(id=busqueda_numero)
        
        except ValueError:
            pedidos = Pedido.objects.none()

    return render(request, 'pedido/pedidos.html', {
        'pedidos': pedidos,
        'busqueda_fecha': busqueda_fecha,
        'busqueda_numero': busqueda_numero,
        'mostrar_botonPdf': mostrar_botonPdf
    })

def actualizarEstadoPedido(request,pedido_id,caracter):
    pedido = get_object_or_404(Pedido, id=pedido_id)
    if caracter == 'c':
        pedido.estadoPedido = 'confirmado'
    elif caracter == 'p':
        pedido.estadoPedido = 'pendiente'
    elif caracter == 'x':
        pedido.estadoPedido = 'cancelado'    
    pedido.save()
    return redirect('pedidos:pedidos')

class PDFPedido(FPDF):
    def header(self):
        logo = os.path.join(settings.BASE_DIR, 'static', 'img', 'logotipo.png')
        
        # Verificar si el archivo existe
        if os.path.exists(logo):
            self.image(logo, x=10, y=10, w=30, h=30) 
        
        self.set_font('Arial', '', 15)

        tcol_set(self, 'red')
        tfont_size(self,30)
        tfont(self,'B')
        self.cell(w = 0, h = 10, txt = 'Reporte de', border = 0, ln=1,
                align = 'C', fill = 0)
        self.cell(w = 0, h = 10, txt = 'Pedidos', border = 0, align = 'C', ln=1, fill = 0)
        
        tfont_size(self,10)
        tcol_set(self, 'black')
        tfont(self,'I')
        self.cell(w = 0, h = 10, txt = f'Generado el {datetime.now().strftime("%d/%m/%y")}', border = 0, ln=2,
                align = 'C', fill = 0)

        self.ln(5)

    # Page footer
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-20)

        # Arial italic 8
        self.set_font('Arial', 'I', 12)

        # Page number
        self.cell(w = 0, h = 10, txt =  'Pagina ' + str(self.page_no()),
                 border = 0,
                align = 'C', fill = 0)

def generarPDFPedidos(request):
    # Crear un objeto FPDF
    pdf = PDFPedido()
    pdf.add_page()
    
    busqueda_fecha = request.session.get('busqueda_fecha', None)
    busqueda_numero = request.session.get('busqueda_numero', None)
    pedidos = Pedido.objects.all()

apps/pedidos/templates/recepcionPedido/detalleRecepcionPedido.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
    <div class="contenedor-agregarVenta d-flex justify-content-center align-items-center">
        <div class="table-responsive">
            <h2 class="text-center">Detalles Recepcion de Pedido</h2>
            <table class="table">
                <div><strong>Número de Pedido: {{recepcionPedido.pedido.id}}</strong></div>
                <div><strong>Recibe: {{recepcionPedido.empleado}}</strong></div>
                <div><strong>Fecha: {{recepcionPedido.fechaDeRecepcion}}</strong></div>

                <thead class="bg-table">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Insumo</th>
                        <th scope="col">Unidad Medida</th>
                        <th scope="col">Cantidad Pedida</th>
                        <th scope="col">Cantidad Recibida</th>
                        <th scope="col">Estado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for detalleRecepcion in detallesRecepcionPedido %} 
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ detalleRecepcion.detallePedido.insumos }}</td>
                        <td>{{ detalleRecepcion.detallePedido.insumos.unidadDeMedida }}</td>
                        <td>{{ detalleRecepcion.detallePedido.cantidadPedida }}</td>
                        <td>{{ detalleRecepcion.cantidadRecibida }}</td>
                        <td>{{ detalleRecepcion.estado }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">No hay detalles de recepción del pedido disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center align-items-center">
        <a href="{% url 'pedidos:recepcionDePedido' recepcionPedido.pedido.id %}" class="btn-volver"><i class="fa-solid fa-arrow-left"></i> Volver</a>
        <br><br>
    </div>
    
{% endblock %}

apps/pedidos/templates/recepcionPedido/recepcionDelPedido.html
{%extends 'base/base.html'%}
{% load static %}

{% block contenido %}
<div class="container" id="container-tabla">
    <div class="col-12">
        <h2 class="text-center pb-3">Recepción de Pedido {{ pedido.id }}</h2>
        <div class="busqueda d-flex">
            <div class="d-flex align-items-center justify-content-center">
                <a href="{% url 'pedidos:recepcionDePedido' pedido.id %}"><i class="fa-solid fa-rotate-left" id="recargaPagRecepcion" title="Recargar página" style="font-size: 25px;color:#a63348"></i></a>
            </div>
            
            {% if mostrar_boton %}
            <div class="btn-modal">
                <button
                    type="button"
                    class="btn"
                    data-bs-toggle="modal"
                    data-bs-target="#exampleModal"
                >
                    <i
                        class="fa-solid fa-square-plus"
                        title="Agregar Proveedor"
                        style="font-size: 30px"
                    >
                    </i>
                </button>
            </div>
            {% endif %}
            <a class="expPdf" href="{% url 'pedidos:generarPDFrecepcion' pedido.id%}"
            ><i class="fa-solid fa-file-pdf px-2" style="font-size: 25px"></i
            >Exportar PDF</a>
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead class="bg-table">
                    <tr>
                        <th scope="col">Proveedor</th>
                        <th scope="col">Fecha Pedido</th>
                        <th scope="col">Estado Pedido</th>
                        <th scope="col">Total</th>
                        <th scope="col">Detalle Pedido</th>
                        <th scope="col">Estado Recepción</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ pedido.proveedor }}</td>
                        <td>{{ pedido.fechaPedido|date:"d/m/Y" }}</td>
                        {% if pedido.estadoPedido == 'cancelado' %}
                        <td style="background-color: #d81111;">{{ pedido.estadoPedido }}</td>{% endif %}
                        {% if pedido.estadoPedido == 'pendiente' %}
                        <td style="background-color: #e4f352;">{{ pedido.estadoPedido }}</td>{% endif %}
                        {% if pedido.estadoPedido == 'confirmado' %}
                        <td style="background-color: #4bf156;">{{ pedido.estadoPedido }}</td>{% endif %}
                        <td>{{ pedido.precioTotalDelPedido }}</td>
                        <td>
                            <a href="{% url 'pedidos:verDetallePedidoDesdeRecepcion' pedido.id %}"><i class="fa-solid fa-eye" title="Ver detalles Pedido"></i></a>
                        </td>
                        <td>
                            {% if celdaRecepcion %} 
                            <a href="{% url 'pedidos:verDetallesRecepcionPedido' pedido.id %}"><i class="fa-solid fa-eye" title="Ver detalles Recepcion"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% if not pedido %} 
                    <tr>
                        <td colspan="10">No hay pedidos disponibles.</td>
                    </tr>
                    {% endif %}
                    {% if mensaje %}
                        <tr>
                            <td colspan="10">
                                <div class="alert alert-warning" role="alert">
                                    {{ mensaje }}
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <a href="{% url 'pedidos:pedidos' %}" class="btn-volver"><i class="fa-solid fa-arrow-left"></i> Volver</a>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Registro Recepción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ recepPedidoForm.as_p }}

                    {% for detalle in detallesPedido %}
                        <h3 class="text-center" style="color: #a63348;font-size: 20px;;">Detalle {{ detalle.id }}</h3>
                        <div>
                            <label class="form-control">Insumo: {{ detalle.insumos.nombre }}</label><br>
                            <input type="hidden" name="detallePedido-{{ forloop.counter0 }}" value="{{ detalle.id }}">
                            <label class="form-control">Cantidad Pedida: {{ detalle.cantidadPedida }}</label><br>
                            <label class="form-label" for="cantidadRecibida-{{ forloop.counter0 }}">Cantidad Recibida:</label><br>
                            <input class="form-control" type="number" name="cantidadRecibida-{{ forloop.counter0 }}" value="0" min="0" required>
                        </div><br>
                    {% endfor %}
                    <button type="submit" class="btn w-100 mt-3 btn-addProv">Guardar Recepción</button>
                    <button type="button" class="btn btncancelProv w-100 mt-2" data-bs-dismiss="modal" aria-label="Close">Cancelar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div
    class="modal fade"
    id="deleteModal"
    tabindex="-1"
    aria-labelledby="eliminarModal"
    aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="eliminarModal">
                    <i class="fa-solid fa-circle-exclamation"></i>
                    ATENCIÓN
                </h1>
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                ></button>
            </div>
            <div class="modal-body">¿Estás seguro de eliminar el registro?</div>
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn bg-secundario"
                    data-bs-dismiss="modal"
                    id="btn-cancel"
                >Cerrar
                </button>
                <button type="button" class="btn bg-primario" id="btn-del">
                Eliminar
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Obtener la fecha del pedido desde el template
            const fechaPedido = '{{ pedido.fechaPedido|date:"Y-m-d" }}';  // Formato YYYY-MM-DD
            const inputFechaRecepcion = document.getElementById('id_fechaDeRecepcion');

            // Establecer el atributo min del input de fecha
            inputFechaRecepcion.setAttribute('min', fechaPedido);
        });
    </script>
{% endblock %}   