Panaderia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.inicio.urls')),
    path('productos/',include('apps.productos.urls')),
    path('',include('apps.pedidos.urls')),
    path('ventas/',include('apps.ventas.urls')),
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('empleados/',include('apps.usuarios.urls')),
]

apps/ventas/urls.py
from django.urls import path
from . import views,views_mayoristas
from django.contrib.auth.decorators import login_required

app_name='ventas'

urlpatterns = [
    path('',login_required(views.ventas),name='ventas'),
    path('agregarVenta/',login_required(views.agregarVenta) ,name='agregarVenta'),
    path('verDetallesVenta/<venta_id>',login_required(views.verDetallesVenta),name='verDetallesVenta'),
    path('buscarVentas/',login_required(views.buscarVentas),name='buscarVentas'),
    path('exportarPDF/',login_required(views.exportarPDF),name='exportarPDF'),
    path('listadoMayoristas/',login_required(views_mayoristas.listadoMayoristas),name='listadoMayoristas'),
    path('agregarMayorista/',login_required(views_mayoristas.agregarMayorista),name='agregarMayorista'),
    path('editarMayorista/<mayorista_id>',login_required(views_mayoristas.editarMayorista),name='editarMayorista'),
    path('edicionMayorista/',login_required(views_mayoristas.edicionMayorista),name='edicionMayorista'),
    path('buscarMayorista/',login_required(views_mayoristas.buscarMayorista),name='buscarMayorista'),
    path('exportarPDF_Mayoristas/',login_required(views_mayoristas.exportarPDF_Mayoristas),name='exportarPDF_Mayoristas'),
    path('obtener-precio-producto/<producto_id>/', login_required(views.obtener_precio_producto), name='obtener_precio_producto'),
    path('exportarPDF_ProductosMasVendidos',login_required(views.exportarPDF_ProductosMasVendidos),name='exportarPDF_ProductosMasVendidos'),
] 

#Ver tema de permisos con los empleados

apps/ventas/models.py
from django.db import models
from apps.usuarios.models import Persona, Empleado
from apps.productos.models import Producto
from decimal import Decimal
# Create your models here.

class ClienteMayorista(Persona):
    cuil = models.CharField(max_length=13,blank=False, null=False)
    
    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.cuil}"

class Venta(models.Model):
    TIPO_COMPROBANTE = [
        ('A', 'Factura A'),
        ('B', 'Factura B'),
        ('C', 'Factura C'),
    ]
    FORMA_PAGO = [
        ('efectivo','Efectivo'),
        ('transferencia','Transferencia'),
        ('débito','Débito'),
        ('crédito','Crédito'),
    ]
    fechaDeVenta = models.DateField(blank=False, null=False)
    formaDePago = models.CharField(max_length=15, choices=FORMA_PAGO,blank=False, null=False)
    tipoDeComprobante = models.CharField(max_length=15, choices=TIPO_COMPROBANTE,blank=False, null=False)
    clienteMayorista = models.ForeignKey(ClienteMayorista, on_delete=models.SET_NULL, null=True, blank=True,related_name='clienteMayorista')
    total = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE,related_name='ventaEmpleado')
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Guarda primero la instancia
    
    def calcular_total(self):
        # Calcula el total de todos los detalles de la venta
        self.total = sum(detalle.subTotal for detalle in self.detalleVenta.all())
        self.save(update_fields=['total'])  # Guarda solo el campo total
    
    def __str__(self):
        if self.clienteMayorista is None:
            return f"Venta a consumidor final - {self.fechaDeVenta}"
        else:
            return f"Venta a mayorista {self.clienteMayorista.nombre} - {self.fechaDeVenta}"

class DetalleVenta(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE,related_name='detalleProducto')
    venta = models.ForeignKey(Venta,on_delete=models.CASCADE,related_name='detalleVenta')
    cantidad = models.DecimalField(max_digits=10, decimal_places=2,blank=False, null=False)
    subTotal = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    
    def save(self, *args, **kwargs):
        self.subTotal = self.cantidad * self.producto.precioDeVenta
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.producto.nombre} {self.cantidad} {self.subTotal}"
    

apps/ventas/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from .models import ClienteMayorista, Venta,DetalleVenta

class FormularioVenta(forms.ModelForm):
    class Meta:
        model = Venta
        fields = [
            'fechaDeVenta', 
            'formaDePago', 
            'tipoDeComprobante', 
            'clienteMayorista', 
            
        ]
        labels = {
            'fechaDeVenta': 'Fecha de venta',
            'formaDePago': 'Forma de pago',
            'tipoDeComprobante': 'Tipo de comprobante',
            'clienteMayorista': 'Cliente mayorista',
        }  
        widgets = {
            'fechaDeVenta': forms.TextInput(attrs={'type': 'date','class': 'form-control'}),
            'formaDePago': forms.Select(attrs={'class': 'form-control'}),
            'tipoDeComprobante': forms.Select(attrs={'class': 'form-control'}),
            'clienteMayorista': forms.Select(attrs={'type': 'date','class': 'form-control'}),
        }
        
class DetalleVentaForm(forms.ModelForm):
    class Meta:
        model = DetalleVenta
        fields = ['producto', 'cantidad']
        labels = {
            'producto': 'Producto',
            'cantidad': 'Cantidad',
        }
        widgets = {
            'producto': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control','step': '0.01'}),
        }
    
    def clean_cantidad(self):
        cantidad = self.cleaned_data.get('cantidad')
        producto = self.cleaned_data.get('producto')
        
        if cantidad > producto.cantidadDisponible:
            raise forms.ValidationError(f"Solo hay {producto.cantidadDisponible} unidades disponibles de {producto.nombre}.")
        
        return cantidad

DetalleVentaFormSet = inlineformset_factory(
    Venta, 
    DetalleVenta,  # Venta y DetalleVenta son los modelos relacionados
    form=DetalleVentaForm,
    extra=1,  # comienza mostrando 1 formulario
    can_delete=True  # permite borrar el formulario
)

class FormularioMayorista(forms.ModelForm):
    class Meta:
        model = ClienteMayorista
        fields = ['nombre', 'apellido','cuil', 'direccion','telefono', 'mail']
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'cuil': 'CUIL',
            'direccion': 'Dirección',
            'telefono': 'Teléfono',
            'mail': 'Email',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'cuil': forms.TextInput(attrs={'class': 'form-control','maxlength': '13'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'mail': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/ventas/views.py
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from apps.ventas.models import Venta,DetalleVenta
from apps.ventas.forms import FormularioVenta,DetalleVentaFormSet
from apps.usuarios.models import Empleado
from fpdf import FPDF
from datetime import datetime
import os
from django.http import HttpResponse,JsonResponse
from apps.productos.models import Producto
from django.db.models import Sum

def ventas(request):
    ventas = Venta.objects.all()
    return render(request,'ventas/ventas.html',{'ventas':ventas})

def agregarVenta(request):
    if request.method == 'POST':
        ventaForm = FormularioVenta(request.POST)
        detalleVentaFormset = DetalleVentaFormSet(request.POST)
        
        if ventaForm.is_valid() and detalleVentaFormset.is_valid():

            empleado = get_object_or_404(Empleado, user=request.user)
            venta = ventaForm.save(commit=False)  # No guardar todavía la venta
            venta.empleado = empleado  
            venta.save()  
            totalVenta = 0
            detalles = detalleVentaFormset.save(commit=False) # No guardar todavía los detalles
            
            for detalle in detalles: 
                detalle.venta = venta
                detalle.subTotal = detalle.cantidad * detalle.producto.precioDeVenta
                totalVenta += detalle.subTotal
                producto = detalle.producto
                producto.cantidadDisponible -= detalle.cantidad
                producto.save() #acá vamos a actualizar la cantidad disponible de cada producto cuando se realice una venta
                detalle.save()  #acá guardamos cada detalle de venta
            
            venta.total = totalVenta
            venta.save() #acá se actualiza la venta con todos los detalles de venta y se actualiza el precio total de la venta
            return redirect('/ventas')
    else:
        ventaForm = FormularioVenta()
        detalleVentaFormset = DetalleVentaFormSet()

    return render(request, 'ventas/agregarVenta.html', {'ventaForm': ventaForm,'detalleVentaFormset': detalleVentaFormset,})


def verDetallesVenta(request,venta_id):
    detallesVenta = DetalleVenta.objects.filter(venta_id=venta_id)
    venta = Venta.objects.get(id=venta_id)
    return render(request,'ventas/verDetallesVenta.html',{'detallesVenta':detallesVenta,'venta_id':venta_id,'venta':venta})
    

from django.shortcuts import render
from .models import ClienteMayorista, Venta

def buscarVentas(request):
    ventas = Venta.objects.all()
    fecha_inicio = request.POST.get('fecha_inicio')
    fecha_fin = request.POST.get('fecha_fin')

    # Lógica de filtrado
    if fecha_inicio and fecha_fin:
        # Filtra por rango de fechas
        ventas = ventas.filter(fechaDeVenta__range=[fecha_inicio, fecha_fin])
    elif fecha_inicio:
        # Si solo se ingresa fecha de inicio, filtra por esa fecha exacta
        ventas = ventas.filter(fechaDeVenta=fecha_inicio)
    else:
        return redirect('/ventas')

    return render(request, 'ventas/ventas.html', {'ventas': ventas, 'fecha_inicio': fecha_inicio, 'fecha_fin': fecha_fin})



def diccionario_colores(color): 
    colores = {
        'black' : (0,0,0), 
        'white' : (255,255,255),
        'green' : (96,218,117),
        'blue' : (96,181,218),
        'red': (119,30,48),
        'rose': (214,74,236),
        'gray': (103,103,103),
        'gray2': (233,233,233),
    }
    return colores[color]

def dcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_draw_color(r= cr, g = cg, b= cb)

def bcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_fill_color(r= cr, g = cg, b= cb)

def tcol_set(hoja, color):
    cr, cg, cb = diccionario_colores(color)
    hoja.set_text_color(r= cr, g = cg, b= cb)

def tfont_size(hoja, size):
    hoja.set_font_size(size)

def tfont(hoja, estilo, fuente='Arial'):
    hoja.set_font(fuente, style=estilo)

class PDF(FPDF):
    def __init__(self, title):
        super().__init__()
        self.title = title
    
    def header(self):
        logo = os.path.join(settings.BASE_DIR, 'static', 'img', 'logotipo.png')
        
        # Verificar si el archivo existe
        if os.path.exists(logo):
            self.image(logo, x=10, y=10, w=30, h=30) 
        
        self.set_font('Arial', '', 15)

        tcol_set(self, 'red')
        tfont_size(self,30)
        tfont(self,'B')
        self.cell(w = 0, h = 20, txt = self.title, border = 0, ln=1,
                align = 'C', fill = 0)

        tfont_size(self,10)
        tcol_set(self, 'black')
        tfont(self,'I')
        self.cell(w = 0, h = 10, txt = f'Generado el {datetime.now().strftime("%d/%m/%y")}', border = 0, ln=2,
                align = 'C', fill = 0)

        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 12)
        self.cell(w = 0, h = 10, txt =  'Pagina ' + str(self.page_no()),
                 border = 0,align = 'C', fill = 0)

def exportarPDF(request):
    pdf = PDF('Registro de ventas')
    pdf.add_page()
    
    # Configuración de la tabla
    bcol_set(pdf, 'red')  # Fondo rojo para los títulos de la tabla
    tcol_set(pdf, 'white')
    pdf.set_font("Arial", "B", 12)

    # Dibujar las celdas de los títulos con fondo rojo
    pdf.cell(35, 10, "Fecha de Venta", 1, 0, 'C', fill=True)
    pdf.cell(35, 10, "Forma de pago", 1, 0, 'C', fill=True)
    pdf.cell(25, 10, "Factura", 1, 0, 'C', fill=True)
    pdf.cell(40, 10, "Cliente", 1, 0, 'C', fill=True)
    pdf.cell(25, 10, "Total", 1, 0, 'C', fill=True)
    pdf.cell(30, 10, "Empleado", 1, 1, 'C', fill=True)

    tcol_set(pdf, 'black')
    pdf.set_font("Arial", "", 12)

    ventas = Venta.objects.all()

    if ventas.exists():
        c = 0  # Contador para alternar el color de las filas
        for venta in ventas:
            c += 1

            # Alternar el color de fondo entre gris y blanco
            if c % 2 == 0:
                bcol_set(pdf, 'gray2')  # Fila gris
            else:
                bcol_set(pdf, 'white')  # Fila blanca
            
            # Dibujar las celdas con el color de fondo establecido
            fechaVenta = venta.fechaDeVenta.strftime('%Y-%m-%d')
            pdf.cell(35, 10, fechaVenta, 1, 0, 'C', fill=True)
            pdf.cell(35, 10, f"{venta.formaDePago}", 1, 0, 'C', fill=True)  # Sin `.2f`
            pdf.cell(25, 10, f"{venta.tipoDeComprobante}", 1, 0, 'C', fill=True)
            if venta.clienteMayorista is None:
               pdf.cell(40, 10, "Consumidor Final", 1, 0, 'C', fill=True)
            else:
                pdf.cell(40, 10, f"{venta.clienteMayorista.cuil}", 1, 0, 'C', fill=True)
            pdf.cell(25, 10, f"${venta.total:.2f}", 1, 0, 'C', fill=True)  # Con `.2f` para el total decimal
            pdf.cell(30, 10, f"{venta.empleado.dni}", 1, 1, 'C', fill=True)
    else:
        pdf.cell(0, 10, "No hay productos disponibles.", 0, 1, 'C')

    response = HttpResponse(pdf.output(dest='S').encode('latin1'), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporteVenta.pdf"'
    return response

def obtener_precio_producto(request, producto_id):
    try:
        producto = Producto.objects.get(id=producto_id)
        return JsonResponse({'precio': str(producto.precioDeVenta)})
    except Producto.DoesNotExist:
        return JsonResponse({'error': 'Producto no encontrado'}, status=404)


from django.db.models import Sum
from django.http import HttpResponse

def exportarPDF_ProductosMasVendidos(request):
    pdf = PDF('Productos más vendidos')
    pdf.add_page()
    
    bcol_set(pdf, 'red') 
    tcol_set(pdf, 'white')
    pdf.set_font("Arial", "B", 12)

    pdf.cell(50, 10, "Nombre de producto", 1, 0, 'C', fill=True)
    pdf.cell(50, 10, "Cantidad Vendida", 1, 0, 'C', fill=True)
    pdf.cell(40, 10, "Unidad de medida", 1, 0, 'C', fill=True)
    pdf.cell(50, 10, "Total Vendido", 1, 1, 'C', fill=True)

    # Consulta para obtener productos más vendidos con el total calculado usando el subtotal
    productos_vendidos = (
        DetalleVenta.objects
        .values('producto__nombre', 'producto__unidadDeMedida')
        .annotate(total_vendido=Sum('cantidad'), total_subtotal=Sum('subTotal'))
        .order_by('-total_vendido')
    )

    tcol_set(pdf, 'black')
    pdf.set_font("Arial", "", 12)

    if productos_vendidos:
        for idx, producto in enumerate(productos_vendidos):
            if idx % 2 == 0:
                bcol_set(pdf, 'gray2')  
            else:
                bcol_set(pdf, 'white')  
                
            pdf.cell(50, 10, producto['producto__nombre'], 1, 0, 'C', fill=True)
            pdf.cell(50, 10, f"{producto['total_vendido']:.2f}", 1, 0, 'C', fill=True)
            pdf.cell(40, 10, producto['producto__unidadDeMedida'], 1, 0, 'C', fill=True)
            pdf.cell(50, 10, f"${producto['total_subtotal']:.2f}", 1, 1, 'C', fill=True)
    else:
        pdf.cell(0, 10, "No hay productos disponibles.", 0, 1, 'C')

    response = HttpResponse(pdf.output(dest='S').encode('latin1'), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reporteProductosMasVendidos.pdf"'
    return response


    

apps/ventas/templates/clientes/agregarMayorista.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
    <div class="contenedor-agregarVenta d-flex justify-content-center align-items-center">
        <div class="card-agregarVenta">
            <h3 class="text-center" style="color: #a63348;">Agregar un cliente mayorista</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-addVenta w-100 mt-3">Guardar Mayorista</button>
                <a href="{% url 'ventas:listadoMayoristas' %}" class="btn btn-cancelProd w-100 mt-2">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

apps/ventas/templates/clientes/edicionMayorista.html
{%extends 'base/base.html'%}
{% load static %}

{% block contenido %}

<div class="contenedor-formProd d-flex justify-content-center">
    <div class="card-formProd">
        <form class="row g-3" id="form-prod" action="{% url 'ventas:edicionMayorista' %}" method="post" >{% csrf_token %}
            <h3 class="text-center" style="color: #a63348;">Editar Cliente Mayorista</h3>
            <div class="col-12">
                <input type="hidden" name="id" value="{{ cliente.id }}">
                <label for="nombreClienteRegister" class="form-label"
                    >Nombre</label
                >
                <div class="input-group">
                    <input type="text" name="nombre" class="form-control" id="nombreClienteRegister" value="{{cliente.nombre}}" placeholder="Ingrese nombre del cliente" required/>
                </div>
            </div>
            <label for="nombreClienteRegister" class="labelTxt" id="nombreClienteLabel"></label>

            <div class="col-12">
                <label for="apellidoClienteRegister" class="form-label"
                    >Apellido</label
                >
                <div class="input-group">
                    <input type="text" name="apellido" class="form-control" id="apellidoClienteRegister" value="{{cliente.apellido}}" placeholder="Ingrese apellido del cliente" required/>
                </div>
            </div>
            <label for="apellidoClienteRegister" class="labelTxt" id="apellidoClienteLabel"></label>

            <div class="col-12">
                <label for="cuilClienteRegister" class="form-label"
                    >CUIL</label
                >
                <div class="input-group">
                    <input type="text" name="cuil" class="form-control" id="cuilClienteRegister" value="{{cliente.cuil}}" placeholder="Ingrese CUIL del cliente" required/>
                </div>
            </div>
            <label for="cuilClienteRegister" class="labelTxt" id="cuilclienteLabel"></label>

            <div class="col-12">
                <label for="direccionClienteRegister" class="form-label"
                    >Dirección</label
                >
                <div class="input-group">
                    <input type="text" name="direccion" class="form-control" id="direccionClienteRegister" value="{{cliente.direccion}}" placeholder="Ingrese dirección del cliente" required/>
                </div>
            </div>
            <label for="direccionClienteRegister" class="labelTxt" id="direccionclienteLabel"></label>
            
            <div class="col-12">
                <label for="telefonoClienteRegister" class="form-label"
                    >Teléfono</label
                >
                <div class="input-group">
                    <input type="text" name="telefono" class="form-control" id="telefonoClienteRegister" value="{{cliente.telefono}}" placeholder="Ingrese teléfono del cliente" required/>
                </div>
            </div>
            <label for="telefonoClienteRegister" class="labelTxt" id="telclienteLabel"></label>

            <div class="col-12">
                <label for="mailClienteRegister" class="form-label"
                    >Email</label
                >
                <div class="input-group">
                    <input type="text" name="mail" class="form-control" id="mailClienteRegister" value="{{cliente.mail}}" placeholder="Ingrese email del cliente" required/>
                </div>
            </div>
            <label for="mailClienteRegister" class="labelTxt" id="mailclienteLabel"></label>

            <div class="col-12">
                <button class="btn bg-primario w-100 mt-4" type="submit">Registrar</button>
                <button class="btn bg-secundario w-100 mt-1" type="reset">Restablecer valores</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/ventas/templates/clientes/listadoMayoristas.html
{% extends 'base/base.html' %}
{% load static %}

{% block contenido %}
<div class="container" id="container-tabla">
    <div class="col-12">
        <h2 class="text-center pb-3">Registro de clientes mayoristas</h2>
        <div class="busqueda d-flex justify-content-between align-items-center">
            <form class="d-flex align-items-center" role="search" method="POST" action="{% url 'ventas:buscarMayorista' %}">
                {% csrf_token %}
                
                <input class="form-control mb-3" type="search" placeholder="Buscar por cuil" aria-label="buscar" name="busqueda" value="{{ busqueda|default:'' }}" />
                <button class="btn" type="submit">
                    <i class="fa-solid fa-magnifying-glass" style="font-size: 16px"></i>
                </button>
                <a href="{% url 'ventas:listadoMayoristas' %}" class="ms-2"><i class="fa-solid fa-rotate-left"></i></a>
                  
            </form>
            <a href="{% url 'ventas:agregarMayorista' %}"><i class="fa-solid fa-square-plus" title="Agregar venta" style="font-size: 30px"></i></a>
            <a class="expPdf" href="{% url 'ventas:exportarPDF_Mayoristas' %}"><i class="expPdf fa-solid fa-file-pdf px-2" style="font-size: 25px"></i>Exportar PDF</a>
        </div>
        
        
        
    
        <div class="table-responsive">
            <table class="table">
                <thead class="bg-table">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">CUIL</th>
                        <th scope="col">Dirección</th>
                        <th scope="col">Teléfono</th>
                        <th scope="col">Email</th>
                        <th scope="col">Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %} 
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.apellido }}</td>
                        <td>{{ cliente.cuil }}</td>
                        <td>{{ cliente.direccion }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td>{{ cliente.mail}}</td>
                        <td>
                            <a href="{% url 'ventas:editarMayorista' cliente.id %}"><i class="fa-solid fa-pen-to-square" title="Editar" data-bs-toggle="modal" data-bs-target="#exampleModal"></i></a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="10">No hay ventas disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/tratamientoFechas.js'%}"></script>
{% endblock %}